# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.longrunning_operation import LongrunningOperation  # noqa: E501
from grafeas.rest import ApiException


class TestLongrunningOperation(unittest.TestCase):
    """LongrunningOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLongrunningOperation(self):
        """Test LongrunningOperation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.longrunning_operation.LongrunningOperation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
