# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.api.grafeas_api import GrafeasApi  # noqa: E501
from grafeas.rest import ApiException


class TestGrafeasApi(unittest.TestCase):
    """GrafeasApi unit test stubs"""

    def setUp(self):
        self.api = grafeas.api.grafeas_api.GrafeasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_note(self):
        """Test case for create_note

        Creates a new `Note`.  # noqa: E501
        """
        pass

    def test_create_occurrence(self):
        """Test case for create_occurrence

        Creates a new `Occurrence`. Use this method to create `Occurrences` for a resource.  # noqa: E501
        """
        pass

    def test_create_operation(self):
        """Test case for create_operation

        Creates a new `Operation`.  # noqa: E501
        """
        pass

    def test_get_occurrence_note(self):
        """Test case for get_occurrence_note

        Gets the `Note` attached to the given `Occurrence`.  # noqa: E501
        """
        pass

    def test_list_note_occurrences(self):
        """Test case for list_note_occurrences

        Lists `Occurrences` referencing the specified `Note`. Use this method to get all occurrences referencing your `Note` across all your customer projects.  # noqa: E501
        """
        pass

    def test_list_notes(self):
        """Test case for list_notes

        Lists all `Notes` for a given project.  # noqa: E501
        """
        pass

    def test_list_occurrences(self):
        """Test case for list_occurrences

        Lists active `Occurrences` for a given project matching the filters.  # noqa: E501
        """
        pass

    def test_update_note(self):
        """Test case for update_note

        Updates an existing `Note`.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
