# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.api.grafeas_projects_api import GrafeasProjectsApi  # noqa: E501
from grafeas.rest import ApiException


class TestGrafeasProjectsApi(unittest.TestCase):
    """GrafeasProjectsApi unit test stubs"""

    def setUp(self):
        self.api = grafeas.api.grafeas_projects_api.GrafeasProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Creates a new `Project`.  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Deletes the given `Project` from the system.  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Returns the requested `Project`.  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        Lists `Projects`  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
