# coding: utf-8

"""
    An API to insert and retrieve metadata on cloud artifacts.

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.googlelongrunning_operation import GooglelongrunningOperation  # noqa: E501
from grafeas.rest import ApiException


class TestGooglelongrunningOperation(unittest.TestCase):
    """GooglelongrunningOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGooglelongrunningOperation(self):
        """Test GooglelongrunningOperation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.googlelongrunning_operation.GooglelongrunningOperation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
