# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.pgp_signed_attestation_content_type import PgpSignedAttestationContentType  # noqa: E501
from grafeas.rest import ApiException


class TestPgpSignedAttestationContentType(unittest.TestCase):
    """PgpSignedAttestationContentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPgpSignedAttestationContentType(self):
        """Test PgpSignedAttestationContentType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.pgp_signed_attestation_content_type.PgpSignedAttestationContentType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
