# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.api_cloud_repo_source_context import ApiCloudRepoSourceContext  # noqa: E501
from grafeas.rest import ApiException


class TestApiCloudRepoSourceContext(unittest.TestCase):
    """ApiCloudRepoSourceContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCloudRepoSourceContext(self):
        """Test ApiCloudRepoSourceContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.api_cloud_repo_source_context.ApiCloudRepoSourceContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
