# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.v1beta1package_location import V1beta1packageLocation  # noqa: F401,E501


class PackageInstallation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'location': 'list[V1beta1packageLocation]'
    }

    attribute_map = {
        'name': 'name',
        'location': 'location'
    }

    def __init__(self, name=None, location=None):  # noqa: E501
        """PackageInstallation - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._location = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if location is not None:
            self.location = location

    @property
    def name(self):
        """Gets the name of this PackageInstallation.  # noqa: E501

        Output only. The name of the installed package.  # noqa: E501

        :return: The name of this PackageInstallation.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PackageInstallation.

        Output only. The name of the installed package.  # noqa: E501

        :param name: The name of this PackageInstallation.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def location(self):
        """Gets the location of this PackageInstallation.  # noqa: E501

        Required. All of the places within the filesystem versions of this package have been found.  # noqa: E501

        :return: The location of this PackageInstallation.  # noqa: E501
        :rtype: list[V1beta1packageLocation]
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PackageInstallation.

        Required. All of the places within the filesystem versions of this package have been found.  # noqa: E501

        :param location: The location of this PackageInstallation.  # noqa: E501
        :type: list[V1beta1packageLocation]
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageInstallation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageInstallation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
