# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.package_manager_distribution import PackageManagerDistribution  # noqa: E501
from grafeas.rest import ApiException


class TestPackageManagerDistribution(unittest.TestCase):
    """PackageManagerDistribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageManagerDistribution(self):
        """Test PackageManagerDistribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.package_manager_distribution.PackageManagerDistribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
