# coding: utf-8

"""
    An API to insert and retrieve metadata on cloud artifacts.

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiUpdateOperationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'operation': 'GooglelongrunningOperation'
    }

    attribute_map = {
        'name': 'name',
        'operation': 'operation'
    }

    def __init__(self, name=None, operation=None):  # noqa: E501
        """ApiUpdateOperationRequest - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._operation = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if operation is not None:
            self.operation = operation

    @property
    def name(self):
        """Gets the name of this ApiUpdateOperationRequest.  # noqa: E501

        The name of the Operation. Should be of the form \"projects/{provider_id}/operations/{operation_id}\".  # noqa: E501

        :return: The name of this ApiUpdateOperationRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiUpdateOperationRequest.

        The name of the Operation. Should be of the form \"projects/{provider_id}/operations/{operation_id}\".  # noqa: E501

        :param name: The name of this ApiUpdateOperationRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def operation(self):
        """Gets the operation of this ApiUpdateOperationRequest.  # noqa: E501

        The operation to create.  # noqa: E501

        :return: The operation of this ApiUpdateOperationRequest.  # noqa: E501
        :rtype: GooglelongrunningOperation
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this ApiUpdateOperationRequest.

        The operation to create.  # noqa: E501

        :param operation: The operation of this ApiUpdateOperationRequest.  # noqa: E501
        :type: GooglelongrunningOperation
        """

        self._operation = operation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiUpdateOperationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiUpdateOperationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
