# coding: utf-8

"""
    An API to insert and retrieve metadata on cloud artifacts.

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiStorageSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bucket': 'str',
        'object': 'str',
        'generation': 'str'
    }

    attribute_map = {
        'bucket': 'bucket',
        'object': 'object',
        'generation': 'generation'
    }

    def __init__(self, bucket=None, object=None, generation=None):  # noqa: E501
        """ApiStorageSource - a model defined in Swagger"""  # noqa: E501

        self._bucket = None
        self._object = None
        self._generation = None
        self.discriminator = None

        if bucket is not None:
            self.bucket = bucket
        if object is not None:
            self.object = object
        if generation is not None:
            self.generation = generation

    @property
    def bucket(self):
        """Gets the bucket of this ApiStorageSource.  # noqa: E501

        Google Cloud Storage bucket containing source (see [Bucket Name Requirements] (https://cloud.google.com/storage/docs/bucket-naming#requirements)).  # noqa: E501

        :return: The bucket of this ApiStorageSource.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this ApiStorageSource.

        Google Cloud Storage bucket containing source (see [Bucket Name Requirements] (https://cloud.google.com/storage/docs/bucket-naming#requirements)).  # noqa: E501

        :param bucket: The bucket of this ApiStorageSource.  # noqa: E501
        :type: str
        """

        self._bucket = bucket

    @property
    def object(self):
        """Gets the object of this ApiStorageSource.  # noqa: E501

        Google Cloud Storage object containing source.  # noqa: E501

        :return: The object of this ApiStorageSource.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this ApiStorageSource.

        Google Cloud Storage object containing source.  # noqa: E501

        :param object: The object of this ApiStorageSource.  # noqa: E501
        :type: str
        """

        self._object = object

    @property
    def generation(self):
        """Gets the generation of this ApiStorageSource.  # noqa: E501

        Google Cloud Storage generation for the object.  # noqa: E501

        :return: The generation of this ApiStorageSource.  # noqa: E501
        :rtype: str
        """
        return self._generation

    @generation.setter
    def generation(self, generation):
        """Sets the generation of this ApiStorageSource.

        Google Cloud Storage generation for the object.  # noqa: E501

        :param generation: The generation of this ApiStorageSource.  # noqa: E501
        :type: str
        """

        self._generation = generation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiStorageSource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiStorageSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
