# coding: utf-8

"""
    An API to insert and retrieve metadata on cloud artifacts.

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiProjectRepoId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'str',
        'repo_name': 'str'
    }

    attribute_map = {
        'project_id': 'project_id',
        'repo_name': 'repo_name'
    }

    def __init__(self, project_id=None, repo_name=None):  # noqa: E501
        """ApiProjectRepoId - a model defined in Swagger"""  # noqa: E501

        self._project_id = None
        self._repo_name = None
        self.discriminator = None

        if project_id is not None:
            self.project_id = project_id
        if repo_name is not None:
            self.repo_name = repo_name

    @property
    def project_id(self):
        """Gets the project_id of this ApiProjectRepoId.  # noqa: E501

        The ID of the project.  # noqa: E501

        :return: The project_id of this ApiProjectRepoId.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ApiProjectRepoId.

        The ID of the project.  # noqa: E501

        :param project_id: The project_id of this ApiProjectRepoId.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def repo_name(self):
        """Gets the repo_name of this ApiProjectRepoId.  # noqa: E501

        The name of the repo. Leave empty for the default repo.  # noqa: E501

        :return: The repo_name of this ApiProjectRepoId.  # noqa: E501
        :rtype: str
        """
        return self._repo_name

    @repo_name.setter
    def repo_name(self, repo_name):
        """Sets the repo_name of this ApiProjectRepoId.

        The name of the repo. Leave empty for the default repo.  # noqa: E501

        :param repo_name: The repo_name of this ApiProjectRepoId.  # noqa: E501
        :type: str
        """

        self._repo_name = repo_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiProjectRepoId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiProjectRepoId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
