# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.source_repo_id import SourceRepoId  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceRepoId(unittest.TestCase):
    """SourceRepoId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceRepoId(self):
        """Test SourceRepoId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.source_repo_id.SourceRepoId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
