# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.image_layer import ImageLayer  # noqa: E501
from swagger_client.rest import ApiException


class TestImageLayer(unittest.TestCase):
    """ImageLayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageLayer(self):
        """Test ImageLayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.image_layer.ImageLayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
