# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.source_git_source_context import SourceGitSourceContext  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceGitSourceContext(unittest.TestCase):
    """SourceGitSourceContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceGitSourceContext(self):
        """Test SourceGitSourceContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.source_git_source_context.SourceGitSourceContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
