# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.image_fingerprint import ImageFingerprint  # noqa: E501
from swagger_client.rest import ApiException


class TestImageFingerprint(unittest.TestCase):
    """ImageFingerprint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageFingerprint(self):
        """Test ImageFingerprint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.image_fingerprint.ImageFingerprint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
