# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.authority_hint import AuthorityHint  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthorityHint(unittest.TestCase):
    """AuthorityHint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorityHint(self):
        """Test AuthorityHint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.authority_hint.AuthorityHint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
