# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1beta1_note import V1beta1Note  # noqa: E501
from swagger_client.rest import ApiException


class TestV1beta1Note(unittest.TestCase):
    """V1beta1Note unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1Note(self):
        """Test V1beta1Note"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1beta1_note.V1beta1Note()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
