# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.source_cloud_repo_source_context import SourceCloudRepoSourceContext  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceCloudRepoSourceContext(unittest.TestCase):
    """SourceCloudRepoSourceContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceCloudRepoSourceContext(self):
        """Test SourceCloudRepoSourceContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.source_cloud_repo_source_context.SourceCloudRepoSourceContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
