# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from grafeas.models.api_artifact import ApiArtifact  # noqa: F401,E501
from grafeas.models.api_command import ApiCommand  # noqa: F401,E501
from grafeas.models.api_source import ApiSource  # noqa: F401,E501


class ApiBuildProvenance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'project_id': 'str',
        'commands': 'list[ApiCommand]',
        'built_artifacts': 'list[ApiArtifact]',
        'create_time': 'datetime',
        'start_time': 'datetime',
        'finish_time': 'datetime',
        'creator': 'str',
        'logs_bucket': 'str',
        'source_provenance': 'ApiSource',
        'trigger_id': 'str',
        'build_options': 'dict(str, str)',
        'builder_version': 'str'
    }

    attribute_map = {
        'id': 'id',
        'project_id': 'project_id',
        'commands': 'commands',
        'built_artifacts': 'built_artifacts',
        'create_time': 'create_time',
        'start_time': 'start_time',
        'finish_time': 'finish_time',
        'creator': 'creator',
        'logs_bucket': 'logs_bucket',
        'source_provenance': 'source_provenance',
        'trigger_id': 'trigger_id',
        'build_options': 'build_options',
        'builder_version': 'builder_version'
    }

    def __init__(self, id=None, project_id=None, commands=None, built_artifacts=None, create_time=None, start_time=None, finish_time=None, creator=None, logs_bucket=None, source_provenance=None, trigger_id=None, build_options=None, builder_version=None):  # noqa: E501
        """ApiBuildProvenance - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._project_id = None
        self._commands = None
        self._built_artifacts = None
        self._create_time = None
        self._start_time = None
        self._finish_time = None
        self._creator = None
        self._logs_bucket = None
        self._source_provenance = None
        self._trigger_id = None
        self._build_options = None
        self._builder_version = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if project_id is not None:
            self.project_id = project_id
        if commands is not None:
            self.commands = commands
        if built_artifacts is not None:
            self.built_artifacts = built_artifacts
        if create_time is not None:
            self.create_time = create_time
        if start_time is not None:
            self.start_time = start_time
        if finish_time is not None:
            self.finish_time = finish_time
        if creator is not None:
            self.creator = creator
        if logs_bucket is not None:
            self.logs_bucket = logs_bucket
        if source_provenance is not None:
            self.source_provenance = source_provenance
        if trigger_id is not None:
            self.trigger_id = trigger_id
        if build_options is not None:
            self.build_options = build_options
        if builder_version is not None:
            self.builder_version = builder_version

    @property
    def id(self):
        """Gets the id of this ApiBuildProvenance.  # noqa: E501

        Unique identifier of the build.  # noqa: E501

        :return: The id of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiBuildProvenance.

        Unique identifier of the build.  # noqa: E501

        :param id: The id of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def project_id(self):
        """Gets the project_id of this ApiBuildProvenance.  # noqa: E501

        ID of the project.  # noqa: E501

        :return: The project_id of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ApiBuildProvenance.

        ID of the project.  # noqa: E501

        :param project_id: The project_id of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def commands(self):
        """Gets the commands of this ApiBuildProvenance.  # noqa: E501

        Commands requested by the build.  # noqa: E501

        :return: The commands of this ApiBuildProvenance.  # noqa: E501
        :rtype: list[ApiCommand]
        """
        return self._commands

    @commands.setter
    def commands(self, commands):
        """Sets the commands of this ApiBuildProvenance.

        Commands requested by the build.  # noqa: E501

        :param commands: The commands of this ApiBuildProvenance.  # noqa: E501
        :type: list[ApiCommand]
        """

        self._commands = commands

    @property
    def built_artifacts(self):
        """Gets the built_artifacts of this ApiBuildProvenance.  # noqa: E501

        Output of the build.  # noqa: E501

        :return: The built_artifacts of this ApiBuildProvenance.  # noqa: E501
        :rtype: list[ApiArtifact]
        """
        return self._built_artifacts

    @built_artifacts.setter
    def built_artifacts(self, built_artifacts):
        """Sets the built_artifacts of this ApiBuildProvenance.

        Output of the build.  # noqa: E501

        :param built_artifacts: The built_artifacts of this ApiBuildProvenance.  # noqa: E501
        :type: list[ApiArtifact]
        """

        self._built_artifacts = built_artifacts

    @property
    def create_time(self):
        """Gets the create_time of this ApiBuildProvenance.  # noqa: E501

        Time at which the build was created.  # noqa: E501

        :return: The create_time of this ApiBuildProvenance.  # noqa: E501
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiBuildProvenance.

        Time at which the build was created.  # noqa: E501

        :param create_time: The create_time of this ApiBuildProvenance.  # noqa: E501
        :type: datetime
        """

        self._create_time = create_time

    @property
    def start_time(self):
        """Gets the start_time of this ApiBuildProvenance.  # noqa: E501

        Time at which execution of the build was started.  # noqa: E501

        :return: The start_time of this ApiBuildProvenance.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ApiBuildProvenance.

        Time at which execution of the build was started.  # noqa: E501

        :param start_time: The start_time of this ApiBuildProvenance.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def finish_time(self):
        """Gets the finish_time of this ApiBuildProvenance.  # noqa: E501

        Time at which execution of the build was finished.  # noqa: E501

        :return: The finish_time of this ApiBuildProvenance.  # noqa: E501
        :rtype: datetime
        """
        return self._finish_time

    @finish_time.setter
    def finish_time(self, finish_time):
        """Sets the finish_time of this ApiBuildProvenance.

        Time at which execution of the build was finished.  # noqa: E501

        :param finish_time: The finish_time of this ApiBuildProvenance.  # noqa: E501
        :type: datetime
        """

        self._finish_time = finish_time

    @property
    def creator(self):
        """Gets the creator of this ApiBuildProvenance.  # noqa: E501

        E-mail address of the user who initiated this build. Note that this was the user's e-mail address at the time the build was initiated; this address may not represent the same end-user for all time.  # noqa: E501

        :return: The creator of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this ApiBuildProvenance.

        E-mail address of the user who initiated this build. Note that this was the user's e-mail address at the time the build was initiated; this address may not represent the same end-user for all time.  # noqa: E501

        :param creator: The creator of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._creator = creator

    @property
    def logs_bucket(self):
        """Gets the logs_bucket of this ApiBuildProvenance.  # noqa: E501

        Google Cloud Storage bucket where logs were written.  # noqa: E501

        :return: The logs_bucket of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._logs_bucket

    @logs_bucket.setter
    def logs_bucket(self, logs_bucket):
        """Sets the logs_bucket of this ApiBuildProvenance.

        Google Cloud Storage bucket where logs were written.  # noqa: E501

        :param logs_bucket: The logs_bucket of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._logs_bucket = logs_bucket

    @property
    def source_provenance(self):
        """Gets the source_provenance of this ApiBuildProvenance.  # noqa: E501

        Details of the Source input to the build.  # noqa: E501

        :return: The source_provenance of this ApiBuildProvenance.  # noqa: E501
        :rtype: ApiSource
        """
        return self._source_provenance

    @source_provenance.setter
    def source_provenance(self, source_provenance):
        """Sets the source_provenance of this ApiBuildProvenance.

        Details of the Source input to the build.  # noqa: E501

        :param source_provenance: The source_provenance of this ApiBuildProvenance.  # noqa: E501
        :type: ApiSource
        """

        self._source_provenance = source_provenance

    @property
    def trigger_id(self):
        """Gets the trigger_id of this ApiBuildProvenance.  # noqa: E501

        Trigger identifier if the build was triggered automatically; empty if not.  # noqa: E501

        :return: The trigger_id of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._trigger_id

    @trigger_id.setter
    def trigger_id(self, trigger_id):
        """Sets the trigger_id of this ApiBuildProvenance.

        Trigger identifier if the build was triggered automatically; empty if not.  # noqa: E501

        :param trigger_id: The trigger_id of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._trigger_id = trigger_id

    @property
    def build_options(self):
        """Gets the build_options of this ApiBuildProvenance.  # noqa: E501

        Special options applied to this build. This is a catch-all field where build providers can enter any desired additional details.  # noqa: E501

        :return: The build_options of this ApiBuildProvenance.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._build_options

    @build_options.setter
    def build_options(self, build_options):
        """Sets the build_options of this ApiBuildProvenance.

        Special options applied to this build. This is a catch-all field where build providers can enter any desired additional details.  # noqa: E501

        :param build_options: The build_options of this ApiBuildProvenance.  # noqa: E501
        :type: dict(str, str)
        """

        self._build_options = build_options

    @property
    def builder_version(self):
        """Gets the builder_version of this ApiBuildProvenance.  # noqa: E501

        Version string of the builder at the time this build was executed.  # noqa: E501

        :return: The builder_version of this ApiBuildProvenance.  # noqa: E501
        :rtype: str
        """
        return self._builder_version

    @builder_version.setter
    def builder_version(self, builder_version):
        """Sets the builder_version of this ApiBuildProvenance.

        Version string of the builder at the time this build was executed.  # noqa: E501

        :param builder_version: The builder_version of this ApiBuildProvenance.  # noqa: E501
        :type: str
        """

        self._builder_version = builder_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiBuildProvenance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
